version: '3'

networks:
  addressbook:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - addressbook

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis

    environment:
      - REDIS_HOST=redis

    networks:
      - addressbook
